import './styles/globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto_Mono, Kaushan_Script } from 'next/font/google'

export const kaushan_script = Kaushan_Script({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-kaushan-script'
  })
export const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
  })
   
export const roboto_mono = Roboto_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto-mono',
  })
  


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}







export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto_mono.variable} ${kaushan_script.variable} scroll-smooth`}>      
      <body>            
      {children}        
      </body>
    </html>
  )
}
