"use client"
import { useRouter } from 'next/navigation';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Page Not Found',
  description: 'Generated by create next app',
}

export default function NotFound() {
  const router = useRouter();
  
  

  

  return (
    
    <div className="flex justify-center items-center flex-col mt-64">
      <h1 className='font-bold text-center uppercase text-3xl'>Not Found</h1>
      <p className='font-bold text-center uppercase text-3xl mt-3'>Sorry, this page does not exist</p>
      <button className="button bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-12" onClick={() => router.push('/')}>Homepage</button>
    </div>
  );
}

function useClient() {
  throw new Error('Function not implemented.');
}
