import { Metadata } from 'next'
import Skills from './compontents/skills'
import About from './compontents/about'
import Projects from './compontents/projects'
import Hero from './compontents/hero'
import Navbar from './compontents/navbar'




export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div>
      <Navbar/>  
      <Hero/>
      <Projects />
      <About/>
      <Skills/>      
    </div>
    

  )
}
